### ISSUE TITLE
[BUG] Infinite cycles in the model

### ISSUE THREAD

**Issue by aworm** [eclipse-esmf/esmf-aspect-model-editor#50]
Version 4.3 stopped supporting cycles in the Aspect Model.
I'm no longer able to generate OpenAPI specification or JSON schema if the created model has infinite cycles.

**Where**
Application error appears in the GUI (screen below - only relevant part is visible), after opening model and also when selecting one of the above mentioned operations.

**Screenshots**
![aspect-model-cycle](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/5788781/22a23b37-bfe8-4f39-b979-ed8d6913b515)

**Additional context**
Old version 4.2.1, didn't generate sample payload for the same model (which makes sens), but I could generate JSON schema and OpenAPI spec.

**Comment by chris-volk** [comment]
Dear @aworm , thanks a lot for creating this issue. We are aware that recursion in Aspect Models is an interesting topic that may receive more fine-tuning in the future. Please let me describe the situation of recursion and the current status and ask you what you are currently trying to achieve.

1. SAMM&Recursion

SAMM is the language for Aspect Models which are models with the purpose to be the basis of APIs that provide semantic information in its payload.
Observations:
Aspect Models containing a "regular" recursion as in your example cannot describe a valid json payload and can therefore not be the basis of any API.
Aspect Models containing a "recursion with circuit breaker" can describe a valid json payload. The "circuit breakers" that SAMM currently has are the Either Characteristic and the optionality of a property. Both of these mean that a valid json payload can have a recursive structure but exist (=be finite) since an optional property may be missing or a property characterised via Either may branch in a non-recursive branch

2. Current Status
- SAMM does not formally disallow recursion yet -- since recursion with circuit breakers has applications and the precise formal definition requires effort 
- SAMM may disallow recursion without circuit breakers in future versions
- The plan is that SAMM will keep allowing recursion with circuit breakers in future versions
- SDK, AME and other tooling support "recursion with circuit breakers" to some degree 
- SDK, AME and other tooling intentionally do not support  "recursion without circuit breakers" since we do not see a usage of creating artifacts for APIs that cannot be implemented (=no valid payload possible). What you see in red text in your screenshot is exactly the intentional error message

3. Your use case

Hope I didn't lose you with the long explanation above. That being said, can you please explain whether you intend to create an Aspect Model containing "recursion with circuit breaker" or an Aspect Model containing recursion without circuit breaker?
If it's the former, can you please provide the model and let us know whether the tooling is working as expected from you?
If it's the latter, then what is your use case? What is the purpose of creating the OpenAPI spec and how do you intend to implement an according API? Thanks for your response.

**Comment by aworm** [comment]
Thanks for the hint, the circuit breaker is perfect solution for us.

One side node, I needed to first mark the Properties as optional and then create the recursion connection. If You first create the connection the Optional flag is not being saved.

**Comment by chris-volk** [comment]
Thanks for your side note, we'll look into this.
